name: Release
on:
  release:
    types: [created]
jobs:
  # build-publish:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v2
  #     - name: Setup Node
  #       uses: actions/setup-node@v2
  #       with:
  #         node-version: '17.x'
  #         registry-url: 'https://registry.npmjs.org'
  #     - name: Install dependencies and test 🔧
  #       run: npm install && npm run test
  #     - name: Publish package on NPM 📦
  #       run: npm publish --access=public
  #       env:
  #         NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
  generate-changelog:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - uses: BobAnkh/auto-generate-changelog@master
      with:
        REPO_NAME: ''
        ACCESS_TOKEN: ${{secrets.GITHUB_TOKEN}}
        PATH: 'CHANGELOG.md'
        COMMIT_MESSAGE: 'docs(CHANGELOG): updated release notes'
        TYPE: 'feat:Features,fix:Patches,docs:Documentation,refactor:Refactor,test:Tests,chore:Others'